# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TerraTech
                                 A QGIS plugin
 Creates training sets for neural networks
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-07-13
        copyright            : (C) 2022 by Sadkov S.A. / TerraTech
        email                : SergeiSadkov@terratech.ru
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TerraTech class from file TerraTech.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Razmetka import TerraTech
    return TerraTech(iface)
